$(".inline").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".koike").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".kobayashi").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".saito").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".sugai").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".habu").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".inoue").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".endo").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".oozono").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".oonuma").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".kousaka").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".seki").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".takemoto").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".tamura").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".fujiyoshi").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".kira").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".matuda").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".moriya").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".morita").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});
$(".yamasaki").modaal({
  background:'#FFF',
  overlay_close:true,
      overlay_opacity:.9,
});

new Vivus('move', {
  type: 'scenario-sync',
  duration: 200,
  forceRender: false,
  animTimingFunction: Vivus.EASE
})